const { chromium } = require('/opt/node22/lib/node_modules/playwright');
const SH = '/tmp/claude-0/-home-user-ArepaMan/8fc33d1f-50c8-5d6b-b4b1-76904f7b8846/scratchpad/shots/';
const mobile = process.argv[2] === 'mobile';
(async () => {
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
  const ctx = await b.newContext({ viewport: mobile ? { width: 390, height: 800 } : { width: 1100, height: 900 }, deviceScaleFactor: 1 });
  const p = await ctx.newPage();
  const errs = [];
  p.on('console', (m) => { if (['error'].includes(m.type()) && !/CERT|404/.test(m.text())) errs.push(m.text()); });
  p.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message));
  const tag = mobile ? 'm-' : 'd-';
  await p.goto('http://localhost:8200/test.html');
  await p.waitForSelector('.todaycard');
  await p.screenshot({ path: SH + tag + '1-dash.png' });
  await p.click('text=Start my first session');
  await p.waitForSelector('.lesson');
  await p.screenshot({ path: SH + tag + '2-lesson.png', fullPage: false });
  await p.click('text=Start practising');
  await p.waitForSelector('.xcard');
  await p.screenshot({ path: SH + tag + '3-ex-predict.png' });
  // wrong answer, hint, then right answer
  await p.fill('textarea.answer', '4 10');
  await p.click('#session .actions .btn.primary');
  await p.waitForSelector('.feedback.bad');
  await p.click('text=/^Hint/');
  await p.screenshot({ path: SH + tag + '4-feedback.png' });
  await p.fill('textarea.answer', '10 4');
  await p.click('#session .actions .btn.primary');
  await p.waitForSelector('.feedback.good');
  await p.waitForSelector('.explain textarea');
  await p.fill('.explain textarea', 'b copied the value 4 at that moment so changing a does not affect it');
  await p.click('text=Compare with the model answer');
  await p.screenshot({ path: SH + tag + '5-explain.png' });
  await p.click('.pt input >> nth=0'); await p.click('.pt input >> nth=1');
  await p.click('#session .explain .btn.primary');
  await p.waitForSelector('text=Continue');
  await p.click('#session >> text=Continue');
  // code exercise
  await p.waitForSelector('.CodeMirror');
  await p.evaluate(() => { document.querySelector('.CodeMirror').CodeMirror.setValue('tickets_open = 12\ntickets_closed = 30\ntotal = 1\n'); });
  await p.click('#session >> text=/^Check$/');
  await p.waitForSelector('.cases', { timeout: 30000 });
  await p.screenshot({ path: SH + tag + '6-code-fail.png' });
  await p.evaluate(() => { document.querySelector('.CodeMirror').CodeMirror.setValue('tickets_open = 12\ntickets_closed = 30\ntotal = tickets_open + tickets_closed\n'); });
  await p.click('#session >> text=/^Check$/');
  await p.waitForSelector('.feedback.good', { timeout: 30000 });
  await p.screenshot({ path: SH + tag + '7-code-pass.png' });
  console.log('state:', JSON.stringify(await p.evaluate(() => ({ c: Object.keys(S().c), p: S().c['py.vars'] && {s: S().c['py.vars'].s, b: S().c['py.vars'].b, d: S().c['py.vars'].d}, py: Engine.py.state })))) ;
  console.log('errors:', JSON.stringify(errs));
  await b.close();
})().catch((e) => { console.error('FLOW FAIL', e.message); process.exit(1); });
